/*
 * Podinate API
 *
 * The API for the simple containerisation solution Podinate
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
	errorHandler ErrorHandler
}

// DefaultApiOption for how the controller is set up.
type DefaultApiOption func(*DefaultApiController)

// WithDefaultApiErrorHandler inject ErrorHandler into controller
func WithDefaultApiErrorHandler(h ErrorHandler) DefaultApiOption {
	return func(c *DefaultApiController) {
		c.errorHandler = h
	}
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer, opts ...DefaultApiOption) Router {
	controller := &DefaultApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{ 
		{
			"ProjectGet",
			strings.ToUpper("Get"),
			"/v0/project",
			c.ProjectGet,
		},
		{
			"ProjectIdGet",
			strings.ToUpper("Get"),
			"/v0/project/{id}",
			c.ProjectIdGet,
		},
		{
			"ProjectIdPatch",
			strings.ToUpper("Patch"),
			"/v0/project/{id}",
			c.ProjectIdPatch,
		},
		{
			"ProjectPost",
			strings.ToUpper("Post"),
			"/v0/project",
			c.ProjectPost,
		},
	}
}

// ProjectGet - Returns a list of projects.
func (c *DefaultApiController) ProjectGet(w http.ResponseWriter, r *http.Request) {
	accountParam := r.Header.Get("account")
	result, err := c.service.ProjectGet(r.Context(), accountParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ProjectIdGet - Get an existing project given by ID
func (c *DefaultApiController) ProjectIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	accountParam := r.Header.Get("account")
	result, err := c.service.ProjectIdGet(r.Context(), idParam, accountParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ProjectIdPatch - Update an existing project
func (c *DefaultApiController) ProjectIdPatch(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	accountParam := r.Header.Get("account")
	result, err := c.service.ProjectIdPatch(r.Context(), idParam, accountParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ProjectPost - Create a new project
func (c *DefaultApiController) ProjectPost(w http.ResponseWriter, r *http.Request) {
	accountParam := r.Header.Get("account")
	appParam := App{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&appParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertAppRequired(appParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ProjectPost(r.Context(), accountParam, appParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
