/*
 * Podinate API
 *
 * The API for the simple containerisation solution Podinate. Login should be performed over oauth from [auth.podinate.com](https://auth.podinate.com)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// PodApiService is a service that implements the logic for the PodApiServicer
// This service should implement the business logic for every endpoint for the PodApi API.
// Include any external packages or services that will be required by this service.
type PodApiService struct {
}

// NewPodApiService creates a default api service
func NewPodApiService() PodApiServicer {
	return &PodApiService{}
}

// ProjectProjectIdPodGet - Get a list of pods for a given project
func (s *PodApiService) ProjectProjectIdPodGet(ctx context.Context, projectId string, account string, page int32, limit int32) (ImplResponse, error) {
	// TODO - update ProjectProjectIdPodGet with the required logic for this service method.
	// Add api_pod_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ProjectProjectIdPodGet200ResponseInner{}) or use other options such as http.Ok ...
	//return Response(200, []ProjectProjectIdPodGet200ResponseInner{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProjectProjectIdPodGet method not implemented")
}

// ProjectProjectIdPodPodIdDelete - Delete a pod
func (s *PodApiService) ProjectProjectIdPodPodIdDelete(ctx context.Context, projectId string, podId string, account string) (ImplResponse, error) {
	// TODO - update ProjectProjectIdPodPodIdDelete with the required logic for this service method.
	// Add api_pod_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(202, Pod{}) or use other options such as http.Ok ...
	//return Response(202, Pod{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProjectProjectIdPodPodIdDelete method not implemented")
}

// ProjectProjectIdPodPodIdGet - Get a pod by ID
func (s *PodApiService) ProjectProjectIdPodPodIdGet(ctx context.Context, projectId string, podId string, account string) (ImplResponse, error) {
	// TODO - update ProjectProjectIdPodPodIdGet with the required logic for this service method.
	// Add api_pod_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Pod{}) or use other options such as http.Ok ...
	//return Response(200, Pod{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProjectProjectIdPodPodIdGet method not implemented")
}

// ProjectProjectIdPodPodIdPatch - Update a pod
func (s *PodApiService) ProjectProjectIdPodPodIdPatch(ctx context.Context, projectId string, podId string, account string, pod Pod) (ImplResponse, error) {
	// TODO - update ProjectProjectIdPodPodIdPatch with the required logic for this service method.
	// Add api_pod_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Pod{}) or use other options such as http.Ok ...
	//return Response(200, Pod{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProjectProjectIdPodPodIdPatch method not implemented")
}

// ProjectProjectIdPodPost - Create a new pod
func (s *PodApiService) ProjectProjectIdPodPost(ctx context.Context, projectId string, account string, pod Pod) (ImplResponse, error) {
	// TODO - update ProjectProjectIdPodPost with the required logic for this service method.
	// Add api_pod_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, Pod{}) or use other options such as http.Ok ...
	//return Response(201, Pod{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProjectProjectIdPodPost method not implemented")
}
