/*
 * Podinate API
 *
 * The API for the simple containerisation solution Podinate.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// ProjectApiController binds http requests to an api service and writes the service results to the http response
type ProjectApiController struct {
	service      ProjectApiServicer
	errorHandler ErrorHandler
}

// ProjectApiOption for how the controller is set up.
type ProjectApiOption func(*ProjectApiController)

// WithProjectApiErrorHandler inject ErrorHandler into controller
func WithProjectApiErrorHandler(h ErrorHandler) ProjectApiOption {
	return func(c *ProjectApiController) {
		c.errorHandler = h
	}
}

// NewProjectApiController creates a default api controller
func NewProjectApiController(s ProjectApiServicer, opts ...ProjectApiOption) Router {
	controller := &ProjectApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ProjectApiController
func (c *ProjectApiController) Routes() Routes {
	return Routes{
		{
			"ProjectGet",
			strings.ToUpper("Get"),
			"/v0/project",
			c.ProjectGet,
		},
		{
			"ProjectIdDelete",
			strings.ToUpper("Delete"),
			"/v0/project/{id}",
			c.ProjectIdDelete,
		},
		{
			"ProjectIdGet",
			strings.ToUpper("Get"),
			"/v0/project/{id}",
			c.ProjectIdGet,
		},
		{
			"ProjectIdPut",
			strings.ToUpper("Put"),
			"/v0/project/{id}",
			c.ProjectIdPut,
		},
		{
			"ProjectPost",
			strings.ToUpper("Post"),
			"/v0/project",
			c.ProjectPost,
		},
	}
}

// ProjectGet - Returns a list of projects.
func (c *ProjectApiController) ProjectGet(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	accountParam := r.Header.Get("account")
	pageParam, err := parseInt32Parameter(query.Get("page"), false)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	limitParam, err := parseInt32Parameter(query.Get("limit"), false)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.ProjectGet(r.Context(), accountParam, pageParam, limitParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ProjectIdDelete - Delete an existing project
func (c *ProjectApiController) ProjectIdDelete(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	accountParam := r.Header.Get("account")
	result, err := c.service.ProjectIdDelete(r.Context(), idParam, accountParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ProjectIdGet - Get an existing project given by ID
func (c *ProjectApiController) ProjectIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	accountParam := r.Header.Get("account")
	result, err := c.service.ProjectIdGet(r.Context(), idParam, accountParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ProjectIdPut - Update an existing project
func (c *ProjectApiController) ProjectIdPut(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	accountParam := r.Header.Get("account")
	projectParam := Project{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&projectParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertProjectRequired(projectParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ProjectIdPut(r.Context(), idParam, accountParam, projectParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ProjectPost - Create a new project
func (c *ProjectApiController) ProjectPost(w http.ResponseWriter, r *http.Request) {
	accountParam := r.Header.Get("account")
	projectParam := Project{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&projectParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertProjectRequired(projectParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ProjectPost(r.Context(), accountParam, projectParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
