/*
 * Podinate API
 *
 * The API for the simple containerisation solution Podinate. Login should be performed over oauth from [auth.podinate.com](https://auth.podinate.com)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserLoginInitGet200Response struct {

	// The URL to redirect the user to
	Url string `json:"url,omitempty"`

	// The token to use to get the user's actual API key once they have completed the oauth flow
	Token string `json:"token,omitempty"`
}

// AssertUserLoginInitGet200ResponseRequired checks if the required fields are not zero-ed
func AssertUserLoginInitGet200ResponseRequired(obj UserLoginInitGet200Response) error {
	return nil
}

// AssertRecurseUserLoginInitGet200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserLoginInitGet200Response (e.g. [][]UserLoginInitGet200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserLoginInitGet200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserLoginInitGet200Response, ok := obj.(UserLoginInitGet200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserLoginInitGet200ResponseRequired(aUserLoginInitGet200Response)
	})
}
