/*
 * Podinate API
 *
 * The API for the simple containerisation solution Podinate
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type ProjectGet500Response struct {

	// The error code for this error
	ErrorCode float32 `json:"error_code,omitempty"`
}

// AssertProjectGet500ResponseRequired checks if the required fields are not zero-ed
func AssertProjectGet500ResponseRequired(obj ProjectGet500Response) error {
	return nil
}

// AssertRecurseProjectGet500ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ProjectGet500Response (e.g. [][]ProjectGet500Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseProjectGet500ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aProjectGet500Response, ok := obj.(ProjectGet500Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertProjectGet500ResponseRequired(aProjectGet500Response)
	})
}
