/*
 * Podinate API
 *
 * The API for the simple containerisation solution Podinate
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	api "github.com/johncave/podinate/api-backend/go"
)

func main() {
	log.Printf("Server started")

	//DefaultApiService := api.NewDefaultApiService()

	DefaultApiService := NewAPIService()
	DefaultApiController := api.NewDefaultApiController(DefaultApiService)

	router := api.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":3000", router))
}
