/*
 * Podinate API
 *
 * The API for the simple containerisation solution Podinate
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	_ "github.com/lib/pq"

	"github.com/johncave/podinate/api-backend/config"
	eh "github.com/johncave/podinate/api-backend/errorhandler"
	"github.com/johncave/podinate/api-backend/router"
)

func main() {
	log.Printf("Server initialising...")

	config.Init()
	log.Println("Server configured...")

	eh.Init()

	theRouter := router.GetRouter()
	log.Fatal(http.ListenAndServe(":3000", theRouter))
	config.Cleanup()
}
