// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/podinate/terraform-provider-podinate/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteProjectProjectIDPodPodIDRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	PodID     string `pathParam:"style=simple,explode=false,name=pod_id"`
	// The account to use for the request
	Account string `header:"style=simple,explode=false,name=account"`
}

func (o *DeleteProjectProjectIDPodPodIDRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *DeleteProjectProjectIDPodPodIDRequest) GetPodID() string {
	if o == nil {
		return ""
	}
	return o.PodID
}

func (o *DeleteProjectProjectIDPodPodIDRequest) GetAccount() string {
	if o == nil {
		return ""
	}
	return o.Account
}

type DeleteProjectProjectIDPodPodIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Request issued incorrectly, for example missing parameters or wrong endpoint
	Error *shared.Error
}

func (o *DeleteProjectProjectIDPodPodIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteProjectProjectIDPodPodIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteProjectProjectIDPodPodIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteProjectProjectIDPodPodIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
