// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/podinate/terraform-provider-podinate/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetUserLoginCompleteRequest struct {
	// The token given by /user/login/init to get the user's actual API key once they have completed the oauth flow
	Token  *string `queryParam:"style=form,explode=true,name=token"`
	Client *string `queryParam:"style=form,explode=true,name=client"`
}

func (o *GetUserLoginCompleteRequest) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

func (o *GetUserLoginCompleteRequest) GetClient() *string {
	if o == nil {
		return nil
	}
	return o.Client
}

// GetUserLoginCompleteResponseBody - An array of pods
type GetUserLoginCompleteResponseBody struct {
	// Whether the user is logged in or not
	LoggedIn *bool `json:"logged_in,omitempty"`
	// The user's API key, if they are logged in
	APIKey *string `json:"api_key,omitempty"`
}

func (o *GetUserLoginCompleteResponseBody) GetLoggedIn() *bool {
	if o == nil {
		return nil
	}
	return o.LoggedIn
}

func (o *GetUserLoginCompleteResponseBody) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

type GetUserLoginCompleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// An array of pods
	Object *GetUserLoginCompleteResponseBody
	// Request issued incorrectly, for example missing parameters or wrong endpoint
	Error *shared.Error
}

func (o *GetUserLoginCompleteResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetUserLoginCompleteResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetUserLoginCompleteResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetUserLoginCompleteResponse) GetObject() *GetUserLoginCompleteResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetUserLoginCompleteResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
