// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/podinate/terraform-provider-podinate/internal/sdk/pkg/models/shared"
	"net/http"
)

type PatchProjectIDRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The account to use for the request
	Account string          `header:"style=simple,explode=false,name=account"`
	Project *shared.Project `request:"mediaType=application/json"`
}

func (o *PatchProjectIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PatchProjectIDRequest) GetAccount() string {
	if o == nil {
		return ""
	}
	return o.Account
}

func (o *PatchProjectIDRequest) GetProject() *shared.Project {
	if o == nil {
		return nil
	}
	return o.Project
}

type PatchProjectIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The was updated successfully, and returned the updated project information
	Project *shared.Project
	// Request issued incorrectly, for example missing parameters or wrong endpoint
	Error *shared.Error
}

func (o *PatchProjectIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchProjectIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchProjectIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchProjectIDResponse) GetProject() *shared.Project {
	if o == nil {
		return nil
	}
	return o.Project
}

func (o *PatchProjectIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
