// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/podinate/terraform-provider-podinate/internal/sdk/pkg/models/shared"
	"net/http"
)

type PatchProjectProjectIDPodPodIDRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	PodID     string `pathParam:"style=simple,explode=false,name=pod_id"`
	// The account to use for the request
	Account string `header:"style=simple,explode=false,name=account"`
	// A JSON object containing the information needed to update a pod
	Pod shared.Pod `request:"mediaType=application/json"`
}

func (o *PatchProjectProjectIDPodPodIDRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *PatchProjectProjectIDPodPodIDRequest) GetPodID() string {
	if o == nil {
		return ""
	}
	return o.PodID
}

func (o *PatchProjectProjectIDPodPodIDRequest) GetAccount() string {
	if o == nil {
		return ""
	}
	return o.Account
}

func (o *PatchProjectProjectIDPodPodIDRequest) GetPod() shared.Pod {
	if o == nil {
		return shared.Pod{}
	}
	return o.Pod
}

type PatchProjectProjectIDPodPodIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The pod was updated successfully
	Pod *shared.Pod
	// Request issued incorrectly, for example missing parameters or wrong endpoint
	Error *shared.Error
}

func (o *PatchProjectProjectIDPodPodIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchProjectProjectIDPodPodIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchProjectProjectIDPodPodIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchProjectProjectIDPodPodIDResponse) GetPod() *shared.Pod {
	if o == nil {
		return nil
	}
	return o.Pod
}

func (o *PatchProjectProjectIDPodPodIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
