// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/podinate/terraform-provider-podinate/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostProjectRequest struct {
	// The account to use for the request
	Account string `header:"style=simple,explode=false,name=account"`
	// A JSON object containing the information needed to create a new project
	Project shared.Project `request:"mediaType=application/json"`
}

func (o *PostProjectRequest) GetAccount() string {
	if o == nil {
		return ""
	}
	return o.Account
}

func (o *PostProjectRequest) GetProject() shared.Project {
	if o == nil {
		return shared.Project{}
	}
	return o.Project
}

type PostProjectResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The project was created successfully
	Project *shared.Project
	// Request issued incorrectly, for example missing parameters or wrong endpoint
	Error *shared.Error
}

func (o *PostProjectResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostProjectResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostProjectResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostProjectResponse) GetProject() *shared.Project {
	if o == nil {
		return nil
	}
	return o.Project
}

func (o *PostProjectResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
