// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/podinate/terraform-provider-podinate/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostUserLoginRequestBody struct {
	// The user's email address
	Username string `json:"username"`
	// The user's password
	Password string `json:"password"`
	// The client name to use for the login
	Client *string `json:"client,omitempty"`
}

func (o *PostUserLoginRequestBody) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *PostUserLoginRequestBody) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *PostUserLoginRequestBody) GetClient() *string {
	if o == nil {
		return nil
	}
	return o.Client
}

// PostUserLoginResponseBody - An array of pods
type PostUserLoginResponseBody struct {
	// Whether the user is logged in or not
	LoggedIn *bool `json:"logged_in,omitempty"`
	// The user's API key, if they are logged in
	APIKey *string `json:"api_key,omitempty"`
}

func (o *PostUserLoginResponseBody) GetLoggedIn() *bool {
	if o == nil {
		return nil
	}
	return o.LoggedIn
}

func (o *PostUserLoginResponseBody) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

type PostUserLoginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// An array of pods
	Object *PostUserLoginResponseBody
	// Request issued incorrectly, for example missing parameters or wrong endpoint
	Error *shared.Error
}

func (o *PostUserLoginResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostUserLoginResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostUserLoginResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostUserLoginResponse) GetObject() *PostUserLoginResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *PostUserLoginResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
