// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/podinate/terraform-provider-podinate/internal/sdk/pkg/models/shared"
)

func (r *PodResourceModel) ToCreateSDKType() *shared.Pod {
	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	image := new(string)
	if !r.Image.IsUnknown() && !r.Image.IsNull() {
		*image = r.Image.ValueString()
	} else {
		image = nil
	}
	tag := new(string)
	if !r.Tag.IsUnknown() && !r.Tag.IsNull() {
		*tag = r.Tag.ValueString()
	} else {
		tag = nil
	}
	status := new(string)
	if !r.Status.IsUnknown() && !r.Status.IsNull() {
		*status = r.Status.ValueString()
	} else {
		status = nil
	}
	createdAt := new(string)
	if !r.CreatedAt.IsUnknown() && !r.CreatedAt.IsNull() {
		*createdAt = r.CreatedAt.ValueString()
	} else {
		createdAt = nil
	}
	resourceID := new(string)
	if !r.ResourceID.IsUnknown() && !r.ResourceID.IsNull() {
		*resourceID = r.ResourceID.ValueString()
	} else {
		resourceID = nil
	}
	out := shared.Pod{
		ID:         id,
		Name:       name,
		Image:      image,
		Tag:        tag,
		Status:     status,
		CreatedAt:  createdAt,
		ResourceID: resourceID,
	}
	return &out
}

func (r *PodResourceModel) ToGetSDKType() *shared.Pod {
	out := r.ToCreateSDKType()
	return out
}

func (r *PodResourceModel) ToUpdateSDKType() *shared.Pod {
	out := r.ToCreateSDKType()
	return out
}

func (r *PodResourceModel) ToDeleteSDKType() *shared.Pod {
	out := r.ToCreateSDKType()
	return out
}

func (r *PodResourceModel) RefreshFromGetResponse(resp *shared.Pod) {
	if resp.CreatedAt != nil {
		r.CreatedAt = types.StringValue(*resp.CreatedAt)
	} else {
		r.CreatedAt = types.StringNull()
	}
	if resp.ID != nil {
		r.ID = types.StringValue(*resp.ID)
	} else {
		r.ID = types.StringNull()
	}
	if resp.Image != nil {
		r.Image = types.StringValue(*resp.Image)
	} else {
		r.Image = types.StringNull()
	}
	if resp.Name != nil {
		r.Name = types.StringValue(*resp.Name)
	} else {
		r.Name = types.StringNull()
	}
	if resp.ResourceID != nil {
		r.ResourceID = types.StringValue(*resp.ResourceID)
	} else {
		r.ResourceID = types.StringNull()
	}
	if resp.Status != nil {
		r.Status = types.StringValue(*resp.Status)
	} else {
		r.Status = types.StringNull()
	}
	if resp.Tag != nil {
		r.Tag = types.StringValue(*resp.Tag)
	} else {
		r.Tag = types.StringNull()
	}
}

func (r *PodResourceModel) RefreshFromCreateResponse(resp *shared.Pod) {
	r.RefreshFromGetResponse(resp)
}

func (r *PodResourceModel) RefreshFromUpdateResponse(resp *shared.Pod) {
	r.RefreshFromGetResponse(resp)
}
