// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/podinate/terraform-provider-podinate/internal/sdk"
	"github.com/podinate/terraform-provider-podinate/internal/sdk/pkg/models/shared"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ provider.Provider = &PodinateProvider{}

type PodinateProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// PodinateProviderModel describes the provider data model.
type PodinateProviderModel struct {
	ServerURL  types.String `tfsdk:"server_url"`
	APIKeyAuth types.String `tfsdk:"api_key_auth"`
}

func (p *PodinateProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "podinate"
	resp.Version = p.version
}

func (p *PodinateProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: `Podinate API: The API for the simple containerisation solution Podinate.`,
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				MarkdownDescription: "Server URL (defaults to https://api.podinate.com/v0)",
				Optional:            true,
				Required:            false,
			},
			"api_key_auth": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
			},
		},
	}
}

func (p *PodinateProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data PodinateProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ServerURL := data.ServerURL.ValueString()

	if ServerURL == "" {
		ServerURL = "https://api.podinate.com/v0"
	}

	apiKeyAuth := data.APIKeyAuth.ValueString()
	security := shared.Security{
		APIKeyAuth: apiKeyAuth,
	}

	opts := []sdk.SDKOption{
		sdk.WithServerURL(ServerURL),
		sdk.WithSecurity(security),
	}
	client := sdk.New(opts...)

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *PodinateProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewPodResource,
		NewProjectResource,
	}
}

func (p *PodinateProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewPodDataSource,
		NewProjectDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &PodinateProvider{
			version: version,
		}
	}
}
