// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type EnvironmentVariable struct {
	Key    types.String `tfsdk:"key"`
	Secret types.Bool   `tfsdk:"secret"`
	Value  types.String `tfsdk:"value"`
}
