apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.10.0.11
      user: ubuntu
      port: 22
      keyPath: /home/ubuntu/.ssh/id_ed25519
    role: controller+worker
    noTaints: true
  - ssh:
      address: 10.10.0.12
      user: ubuntu
      port: 22
      keyPath: /home/ubuntu/.ssh/id_ed25519
    role: controller+worker
    noTaints: true
  - ssh:
      address: 10.10.0.13
      user: ubuntu
      port: 22
      keyPath: /home/ubuntu/.ssh/id_ed25519
    role: controller+worker
    noTaints: true
  k0s:
    version: v1.28.4+k0s.0
    dynamicConfig: false
    config: {}