// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EnvironmentVariable - An environment variable is a key-value pair that is passed to the container when it is run.
type EnvironmentVariable struct {
	// The key of the environment variable
	Key string `json:"key"`
	// The value of the environment variable
	Value string `json:"value"`
	// Whether the value of the environment variable is a secret or not. If it is a secret, it will not be returned in the API response.
	Secret *bool `json:"secret,omitempty"`
}

func (o *EnvironmentVariable) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *EnvironmentVariable) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

func (o *EnvironmentVariable) GetSecret() *bool {
	if o == nil {
		return nil
	}
	return o.Secret
}
