// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Pod - A pod is a group of containers with the same lifecycle, and are the basic unit of deployment on Podinate
type Pod struct {
	// The short name (slug/url) of the pod
	ID *string `json:"id,omitempty"`
	// The name of the pod
	Name *string `json:"name,omitempty"`
	// The container image to run for this pod
	Image *string `json:"image,omitempty"`
	// The image tag to run for this pod
	Tag *string `json:"tag,omitempty"`
	// The current status of the pod
	Status *string `json:"status,omitempty"`
	// The date and time the pod was created
	CreatedAt *string `json:"created_at,omitempty"`
	// The global Resource ID of the pod
	ResourceID *string `json:"resource_id,omitempty"`
}

func (o *Pod) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Pod) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Pod) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

func (o *Pod) GetTag() *string {
	if o == nil {
		return nil
	}
	return o.Tag
}

func (o *Pod) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Pod) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Pod) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}
