// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Project - A project is a container for individual resources. For example the my-cool-blog project might contain a pod running a Wordpress image, a Postgres Neon database, and a bucket for storing uploads.
type Project struct {
	// The short name (slug/url) of the project
	ID *string `json:"id,omitempty"`
	// The name of the app
	Name *string `json:"name,omitempty"`
	// The global Resource ID of the project
	ResourceID *string `json:"resource_id,omitempty"`
}

func (o *Project) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Project) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Project) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}
