// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Service - A service makes a Pod available to other Pods or to the internet
type Service struct {
	// The hostname of the service
	Name string `json:"name"`
	// The port to expose the service on
	Port int64 `json:"port"`
	// The port to forward traffic to, if different from the port. Can be left blank if the same as the port.
	TargetPort *int64 `json:"targetPort,omitempty"`
	// The protocol to use for the service. Either http, tcp or udp.
	Protocol string `json:"protocol"`
	// The domain name to use for the service. If left blank, the service will only be available internally. If set, the service will be available externally at the given domain name.
	DomainName *string `json:"domain_name,omitempty"`
}

func (o *Service) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Service) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *Service) GetTargetPort() *int64 {
	if o == nil {
		return nil
	}
	return o.TargetPort
}

func (o *Service) GetProtocol() string {
	if o == nil {
		return ""
	}
	return o.Protocol
}

func (o *Service) GetDomainName() *string {
	if o == nil {
		return nil
	}
	return o.DomainName
}
