// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Storage - A storage volume that is attached to each instance of a pod.
type Storage struct {
	// The name of the volume
	Name string `json:"name"`
	// The size of the volume in GB
	Size int64 `json:"size"`
	// The path to mount the volume at
	MountPath string `json:"mount_path"`
	// The global Resource ID of the volume
	ResourceID *string `json:"resource_id,omitempty"`
}

func (o *Storage) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Storage) GetSize() int64 {
	if o == nil {
		return 0
	}
	return o.Size
}

func (o *Storage) GetMountPath() string {
	if o == nil {
		return ""
	}
	return o.MountPath
}

func (o *Storage) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}
