// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Volume - A storage volume that is attached to each instance of a pod.
type Volume struct {
	// The name of the volume
	Name string `json:"name"`
	// The size of the volume in GB
	Size int64 `json:"size"`
	// The path to mount the volume at
	MountPath string `json:"mount_path"`
}

func (o *Volume) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Volume) GetSize() int64 {
	if o == nil {
		return 0
	}
	return o.Size
}

func (o *Volume) GetMountPath() string {
	if o == nil {
		return ""
	}
	return o.MountPath
}
