# the kubernetes yaml for a deployment running the image cosmtrek/air
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-deployment
  labels:
    app: api-backend
spec:
  selector:
    matchLabels:
      app: api-backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
        - name: backend
          image: cosmtrek/air
          imagePullPolicy: Always
          command: ["/go/bin/air", "-d"]
          workingDir: /go/src/github.com/johncave/podinate/api-backend
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-backend-env
          env:
            - name : POSTGRES_HOST
              value: mypostgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: masterdb-secret
                  key: superUserPassword
            - name: CONFIG_FILE
              value: /etc/config/config.toml
          volumeMounts:
            - name: api-backend-config
              mountPath: /etc/config
      serviceAccountName: api-backend-deployment-manager
      volumes:
        - name: api-backend-config
          configMap:
            name: api-backend-config
            items:
              - key: config.toml
                path: config.toml
      
      
    

---
apiVersion: v1
kind: Service
metadata:
  name: api-backend
  labels:
    app: api-backend
spec:
  clusterIP: None
  ports:
    - port: 3000
      name: api-backend
  selector:
    app: api-backend

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-backend-env
data:
  PORT: "3000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-backend-config
data:
  config.toml: |
    [database]
    host = "masterdb"
    port = 5432
    user = "postgres"
    database = "podinate"

    [auth]
    api_host = "http://localhost:3001"
    [[gitlab]]
    public_host = "http://gitlab.dev-git.podinate.com:8081"
    internal_host = "http://gitlab-webservice-default.gitlab:8080"


---
# ServiceAccount to give access to manage deployments in all namespaces
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-backend-deployment-manager
  namespace: api
---
# ClusterRole to give access to manage deployments in all namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-backend-deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# ClusterRoleBinding to bind the ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-backend-deployment-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-backend-deployment-manager
subjects:
- kind: ServiceAccount
  name: api-backend-deployment-manager
  namespace: api

