# the kubernetes yaml for a deployment running the image cosmtrek/air
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       — name: backend
         image: cosmtrek/air
         workingDir: /go/src/github.com/johncave/podinate/
         ports:
           —containerPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadMany
  hostPath:
    path: /mnt/code

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    - ReadMany
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi