# the kubernetes yaml for a deployment running the image cosmtrek/air
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-deployment
  labels:
    app: api-backend
spec:
  selector:
    matchLabels:
      app: api-backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
        — name: backend
          image: cosmtrek/air
          // workingDir: /go/src/github.com/johncave/podinate/
          ports:
            — containerPort: 8080
  ---
apiVersion: v1
kind: Service
metadata:
  name: api-backend
  labels:
    app: api-backend
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: api-backend
  selector:
    app: api-backend