# the kubernetes yaml for a deployment running the image cosmtrek/air
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-deployment
  labels:
    app: api-backend
spec:
  selector:
    matchLabels:
      app: api-backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
        - name: backend
          image: cosmtrek/air
          imagePullPolicy: Always
          command: ["/go/bin/air", "-d"]
          workingDir: /go/src/github.com/johncave/podinate/api-backend
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: api-backend
  labels:
    app: api-backend
spec:
  clusterIP: None
  ports:
    - port: 3000
      name: api-backend
  selector:
    app: api-backend

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-backend-env
data:
  PORT: "3000"