# Goerd is what we use to manage postgres schema and migrations 

## Path: kubernetes/goerd.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-script
  namespace: podinate
data:
  migration.sh: |
    #!/bin/sh
    wget https://raw.githubusercontent.com/podinate/podinate/main/database/atlas.hcl
    /atlas schema apply --url "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable" --to file://atlas.hcl --auto-approve

---
apiVersion: batch/v1
kind: Job
metadata:
  name: atlas
  namespace: podinate
  labels:
    app: atlas
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: atlas
          image: arigaio/atlas:latest-alpine
          #command: [ "/migrations/migration.sh" ]
          command: [
            "sh",
            "/migrations/migration.sh"
          ]
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: masterdb-secret
                  key: superUserPassword
            - name: POSTGRES_DB
              value: podinate
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: migration-script
              mountPath: /migrations

      volumes:
        - name: migration-script
          configMap:
            name: migration-script
            items:
              - key: migration.sh
                path: migration.sh
            defaultMode: 0777