# Goerd is what we use to manage postgres schema and migrations 

## Path: kubernetes/goerd.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-script
  namespace: podinate
data:
  migration.sh: |
    #!/bin/sh
    /atlas schema apply --url "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable" --to file://atlas.hcl

---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: atlas
  namespace: podinate
  labels:
    app: atlas
spec:
  selector:
    matchLabels:
      app: atlas
  template:
    metadata:
      labels:
        app: atlas
    spec:
      containers:
        - name: atlas
          image: arigaio/atlas:latest-alpine
          # this is a utility container
          # See the make postgres-migrate target in the Makefile
          command: [
            "sleep", "9999999999999"
          ]
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: masterdb-secret
                  key: superUserPassword
            - name: POSTGRES_DB
              value: podinate
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: migration-script
              mountPath: /migrations

      volumes:
        - name: migration-script
          configMap:
            name: migration-script
            items:
              - key: migration.sh
                path: migration.sh
            defaultMode: 0777