apiVersion: v1
kind: Secret
metadata:
  name: masterdb-secret
  namespace: podinate
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: masterdb
  namespace: podinate

spec:

   replicas: 1
   image: postgres:15.4

   database:
      size: 200Mi

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: masterdb-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: masterdb-secret
              key: replicationUserPassword