/*
Podinate API

The API for the simple containerisation solution Podinate. Login should be performed over oauth from [auth.podinate.com](https://auth.podinate.com)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ProjectGet200ResponseInner - struct for ProjectGet200ResponseInner
type ProjectGet200ResponseInner struct {
	Project *Project
}

// ProjectAsProjectGet200ResponseInner is a convenience function that returns Project wrapped in ProjectGet200ResponseInner
func ProjectAsProjectGet200ResponseInner(v *Project) ProjectGet200ResponseInner {
	return ProjectGet200ResponseInner{
		Project: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ProjectGet200ResponseInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Project
	err = newStrictDecoder(data).Decode(&dst.Project)
	if err == nil {
		jsonProject, _ := json.Marshal(dst.Project)
		if string(jsonProject) == "{}" { // empty struct
			dst.Project = nil
		} else {
			match++
		}
	} else {
		dst.Project = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Project = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ProjectGet200ResponseInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ProjectGet200ResponseInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ProjectGet200ResponseInner) MarshalJSON() ([]byte, error) {
	if src.Project != nil {
		return json.Marshal(&src.Project)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ProjectGet200ResponseInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Project != nil {
		return obj.Project
	}

	// all schemas are nil
	return nil
}

type NullableProjectGet200ResponseInner struct {
	value *ProjectGet200ResponseInner
	isSet bool
}

func (v NullableProjectGet200ResponseInner) Get() *ProjectGet200ResponseInner {
	return v.value
}

func (v *NullableProjectGet200ResponseInner) Set(val *ProjectGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectGet200ResponseInner(val *ProjectGet200ResponseInner) *NullableProjectGet200ResponseInner {
	return &NullableProjectGet200ResponseInner{value: val, isSet: true}
}

func (v NullableProjectGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


