/*
Podinate API

The API for the simple containerisation solution Podinate.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"fmt"
)

// ProjectProjectIdPodGet200ResponseItemsInner - struct for ProjectProjectIdPodGet200ResponseItemsInner
type ProjectProjectIdPodGet200ResponseItemsInner struct {
	Pod *Pod
}

// PodAsProjectProjectIdPodGet200ResponseItemsInner is a convenience function that returns Pod wrapped in ProjectProjectIdPodGet200ResponseItemsInner
func PodAsProjectProjectIdPodGet200ResponseItemsInner(v *Pod) ProjectProjectIdPodGet200ResponseItemsInner {
	return ProjectProjectIdPodGet200ResponseItemsInner{
		Pod: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ProjectProjectIdPodGet200ResponseItemsInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Pod
	err = newStrictDecoder(data).Decode(&dst.Pod)
	if err == nil {
		jsonPod, _ := json.Marshal(dst.Pod)
		if string(jsonPod) == "{}" { // empty struct
			dst.Pod = nil
		} else {
			match++
		}
	} else {
		dst.Pod = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Pod = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ProjectProjectIdPodGet200ResponseItemsInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ProjectProjectIdPodGet200ResponseItemsInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ProjectProjectIdPodGet200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	if src.Pod != nil {
		return json.Marshal(&src.Pod)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ProjectProjectIdPodGet200ResponseItemsInner) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Pod != nil {
		return obj.Pod
	}

	// all schemas are nil
	return nil
}

type NullableProjectProjectIdPodGet200ResponseItemsInner struct {
	value *ProjectProjectIdPodGet200ResponseItemsInner
	isSet bool
}

func (v NullableProjectProjectIdPodGet200ResponseItemsInner) Get() *ProjectProjectIdPodGet200ResponseItemsInner {
	return v.value
}

func (v *NullableProjectProjectIdPodGet200ResponseItemsInner) Set(val *ProjectProjectIdPodGet200ResponseItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectProjectIdPodGet200ResponseItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectProjectIdPodGet200ResponseItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectProjectIdPodGet200ResponseItemsInner(val *ProjectProjectIdPodGet200ResponseItemsInner) *NullableProjectProjectIdPodGet200ResponseItemsInner {
	return &NullableProjectProjectIdPodGet200ResponseItemsInner{value: val, isSet: true}
}

func (v NullableProjectProjectIdPodGet200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectProjectIdPodGet200ResponseItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
