/*
 * Podinate API
 *
 * The API for the simple containerisation solution Podinate. Login should be performed over oauth from [auth.podinate.com](https://auth.podinate.com)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Model404Error struct {

	// The code of the error message (404)
	ErrorCode float32 `json:"error_code,omitempty"`

	// The human-readable description of what went wrong
	ErrorMessage string `json:"error_message,omitempty"`
}

// AssertModel404ErrorRequired checks if the required fields are not zero-ed
func AssertModel404ErrorRequired(obj Model404Error) error {
	return nil
}

// AssertRecurseModel404ErrorRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Model404Error (e.g. [][]Model404Error), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseModel404ErrorRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aModel404Error, ok := obj.(Model404Error)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertModel404ErrorRequired(aModel404Error)
	})
}
