/*
 * Podinate API
 *
 * The API for the simple containerisation solution Podinate
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type App struct {

	// The short name (slug/url) of the project
	Id string `json:"id,omitempty"`

	// The name of the app
	Name string `json:"name,omitempty"`

	// The container image to run for this app
	Image string `json:"image,omitempty"`

	// The image tag to run for this app
	Tag string `json:"tag,omitempty"`
}

// AssertAppRequired checks if the required fields are not zero-ed
func AssertAppRequired(obj App) error {
	return nil
}

// AssertRecurseAppRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of App (e.g. [][]App), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAppRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aApp, ok := obj.(App)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAppRequired(aApp)
	})
}
