site_name: Podinate Documentation
site_url: https://docs.podinate.com

nav:
  - Home: index.md
  - Getting Started: 
    - getting-started/index.md
    - Overview: getting-started/overview.md
    - Concepts: getting-started/concepts.md
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Run Your App: getting-started/your-app.md
    - Add The Team: getting-started/collaborate.md
  - Application Reference:
    - application-reference/index.md
    - WordPress: application-reference/WordPress.md
    - MariaDB: application-reference/MariaDB.md
  - Packages:
    - packages/packages-overview.md
    - Package Structure: packages/package-structure.md
    - Publishing: packages/publishing.md

plugins:
  - tags
#   - social

theme: 
  name: material
  palette: 
    scheme: slate
    primary: deep purple
    accent: cyan
    toggle:
      icon: menu
      name: Menu
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    #- navigation.sections
    - navigation.indexes
    - navigation.path
    - search.suggest